[pytest]
asyncio_mode = auto
filterwarnings =
    ignore:'crypt' is deprecated and slated for removal in Python 3\.13:DeprecationWarning:passlib\..*
    ignore:Accessing the 'model_fields' attribute on the instance is deprecated:pydantic.warnings.PydanticDeprecatedSince211:lazy_model\..*
    ignore:datetime\.datetime\.utcnow\\(\\) is deprecated and scheduled for removal in a future version:DeprecationWarning:jose\.jwt
